### Система рекомендации постов

### Загрузка библиотек и наборов данных

In [1]:
import numpy as np
import pandas as pd
post = pd.read_csv('posts.csv')
user = pd.read_csv('users.csv')
view = pd.read_csv('views.csv')

### Обзор данных и предобработка

In [2]:
user.head()

                        _id                  name gender      academics
0  5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
1  5d610ae1653a331687083239         Gaurav Sharma   male       graduate
2  5d618359fc5fcf3bdd9a0910         Akshay Mishra   male  undergraduate
3  5d6d2bb87fa40e1417a49315        Saksham Mathur   male  undergraduate
4  5d7c994d5720533e15c3b1e9         Varun Chowhan   male  undergraduate

In [3]:
post.head()

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence|Machine Learning|Infor...,blog
2,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
3,5d7d405e5720533e15c3b1f3,Lord Shiva,Drawings,artwork
4,5d80dfbc6c53455f896e600e,How Competition law evolved?,Competition Laws,blog

In [4]:
view.head()

,user_id,post_id,timestamp
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z
1,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z
2,5ed0defa76027d35905cc2de,5eac305f10426255a7aa9dd3,2020-06-01T08:12:42.682Z
3,5ed0defa76027d35905cc2de,5ed1ff0276027d35905cc60d,2020-06-01T08:10:23.880Z
4,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z

In [5]:
print(user.shape)
print(post.shape)
print(view.shape)

(118, 4)
(493, 4)
(1449, 3)

In [6]:
user.describe()

                             _id                  name gender      academics
count                        118                   118    118            118
unique                       118                   118      3              3
top     5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
freq                           1                     1     72             68

In [7]:
post.describe()

                             _id             title     category  post_type
count                        493               493          465        493
unique                       493               477          231          4
top     5d62abaa65218653a132c956  PENCIL RENDERING  Photography    artwork
freq                           1                 3           81        241

In [8]:
post['category'].unique()

array(['Plant Biotechnology',
       'Artificial Intelligence|Machine Learning|Information Technology',
       'Operating Systems', 'Drawings', 'Competition Laws', 'Eco System',
       'Economic Policies', 'Graphic|Graphic Design', 'Painting',
       'Pen and ink', 'Computer Technology|Information Technology',
       'Drawings|Painting',
       'Graphic Design|Visual Arts|Illustration|Graphic',
       'Drawings|Calligraphy', 'Photography', 'Empowerment', nan,
       'Video editing', 'Inorganic Chemistry', 'Programming languages',
       'Conceptual|Graphic Design', 'HR Management',
       'Human Resources|HR Management',
       'Mass Media|International Relations', 'Sculptures|Artistic design',
       'Fashion Design|Ceramics|Artistic design', 'Craft|Artistic design',
       'Fashion Design|Visual Arts|Conceptual|Artistic design',
       'Photography|Fashion Design|Visual Arts|Graphic Design|Artistic design',
       'Fashion Design|Visual Arts|Graphic Design|Artistic design|Graphic|Illustration',
       'Mathematics|Linear Algebra',
       'Electronics & electrical Technology|Electrical Machines',
       'Auditing|Internal Audit', 'E Commerce|E Transactions',
       'Computer Technology|Computation',
       'Auditing|Internal Financial Control', 'Taxation|Custom Laws',
       'Auditing|Audit Evidence', 'Taxation|GST', 'Taxation|Direct Tax',
       'Auditing|Secratarial Audit', 'Banking|Banking Companies',
       'Banking|Banking Technology', 'Auditing|Audit Remark',
       'Auditing|Cost Audit', 'Auditing|Statuary Audit',
       'Computer Technology|Programming languages',
       'Legal Studies|Legal System', 'Sports Coaching|Sports Law',
       'Economics|Economics Sociology', 'Economics|Revenue Concept',
       'Human Rights|Rights and Duties',
       'Sociology|Sociology of Religion', 'Sociology|Sociology in India',
       'Political Science|International Politics',
       'Political Science|Colonialism In India',
       'Legal Studies|Labor Law',
       'Computer Technology|Design and Analysis of Algorithms|Programming languages',
       'Computer Technology|Computer Application|Programming languages|Information Technology',
       'Graphics|Computer Creation', 'E Commerce|Other Online Platforms',
       'Drawing', 'Drawings|Artistic design',
       'Drawings|Artistic design|Illustration',
       'E Commerce|Shopping Platform|Other Online Platforms',
       'Computer Technology|Hardware|Information Technology',
       'Computer Technology|Computation|Computer Application',
       'Business|Business Skills',
       'Computer Technology|Computer Application|Hardware|Information Technology',
       'Computer Technology|Computer Application',
       'Computer Technology|Mobile Applications',
       'Computer Technology|Computer Application|Operating Systems',
       'Computer Technology|Information Technology|Computer Application',
       'Computer Technology|Computer Application|Information Technology',
       'Communication|Basics of Communiaction',
       'Drawings|Painting|Visual Arts|Graphic Design|Prints|Illustration',
       'Drawings|Visual Arts|Painting|Graphic Design|Artistic design|Illustration',
       'Computer Technology|Artificial Intelligence',
       'Marketing|Advertising', 'Political Science|Political Thought',
       'Accounting|Fundamental Of Accounting', 'Mixed Media',
       'Management|Team Mangememnt',
       'Business|Corporate Social Responsibilities',
       'Philosophy|Applied Ethics',
       'Human Resources|Performance In Organization|Organizational Behaviour|HR Management',
       'Fashion Desigining|Fashion Textile|Fashion Manufacturing|Fashion Techniques|Garment Production|Garment Technology',
       'Marketing|Promotion And Distribution Decisions',
       'Biotechnology|Genetic Engineering', 'Physiology|Neurology',
       'Mass Media|Indian Government', 'Physiology|Osteology',
       'Physiology|Cardiology', 'Zoology|Ecology',
       'Computer Technology|Cloud Computing', 'Physiology|Radiology',
       'Computer Technology|Operating Systems',
       'Biotechnology|Molecular Biology',
       'Physiology|Gastroenterology|Cardiology', 'Philosophy|Logic',
       'Watercolours', 'Drawings|Watercolours', 'Mixed Media|Conceptual',
       'Drawings|Painting|Watercolours', 'Visual Arts', 'Conceptual',
       'Tapestry', 'Calligraphy',
       'Human Resources|Performance In Organization',
       'Computer Technology|Robotics|Data Science|Information Technology|Artificial Intelligence',
       'Philosophy|Public Philosophy', 'Digital Marketing',
       'Mass Media|Videography',
       'Drawings|Painting|Visual Arts|Artistic design|Watercolours|Acrylics',
       'Biotechnology|Plant Biotechnology',
       'Sports Coaching|Sports Event',
       'Political Science|Government and Politics',
       'Geography|Physical Geography', 'Computer Technology|Data Science',
       'Computer Technology|Machine Learning', 'Graphic Design',
       'Graphic Design|Visual Arts', 'Education',
       'Business|Business Organisation', 'Zoology|Environmental Biology',
       'Human Rights|Fundamental Rights',
       'Computer Technology|Design and Analysis of Algorithms',
       'Marketing|Marketing Management',
       'Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices',
       'Legal Studies|Income Tax Laws',
       'Graphics|Articulation|Computer Creation',
       'Archeology|Human Prehistory',
       'Business|Start Ups|Entreperneurship|Business Strategies|Venture Capitalist|Business Planning',
       'Geography|Indian Geography',
       'E Commerce|Shopping Platform|Other Online Platforms|Digital India',
       'Business|Bio-entrepreneurship', 'Literature|Stories',
       'History|Indian History', 'ViDEO',
       'Management|Business Management', 'Visual Arts|Photography',
       'Social Work|Health Education', 'Social Work|Social Tech',
       'Social Work|Humanities', 'Photography|Visual Arts',
       'Accounting|Financial Accounting', 'Psycholgy|Social Psychology',
       'Photography|Conceptual', 'Physics|Instrumentation', 'Craft work',
       'Social Work|Social Interventions|Substance Abuse',
       'Economics|Indian Economy',
       'Social Work|Substance Abuse|Social Interventions|Humanities',
       'Social Work|Social Interventions|Substance Abuse|Health Education',
       'Social Work|Humanities|Social Interventions',
       'Finance|Financial Analysis', 'Architecture',
       'Photography|Architecture|Painting',
       'Computer Technology|Cloud Computing|Artificial Intelligence|Information Technology|Programming languages',
       'Computer Technology|Design and Analysis of Algorithms|Web designing|Database Management|Artificial Intelligence',
       'Literature|Movements in Literature',
       'Physics|Atomic Physics|Energy Physics|Quantum Mecahnics|Instrumentation',
       'Business|Business Strategies|Venture Capitalist',
       'Photography|Architecture|Illustration',
       'Photography|Architecture',
       'Human Rights|Fundamental Rights|Protection & Enforcement',
       'Environment Studies|Pollution|Environmental Biology',
       'Photography|Conceptual|Illustration',
       'Physics|Quantum Mecahnics|Industrial Instrumentation|Atomic Physics|Nuclear & Particle Physics|Energy Physics',
       'Biotechnology|Environmental Biotechnology',
       'Legal Studies|Alternate Dispute Resolution|International Treaties|International Agreement',
       'Marketing|Principles Of Marketing|Marketing Research Methadology|Marketing Management|International Marketing',
       'Sculptures', 'Psycholgy|Child Development',
       'Economics|Economic Policies|Break even Point|Foreign Economy',
       'Psycholgy|Psychological Growth',
       'Management|Business Management|Technology Mangement|Managerial Activity|Creative And Lateral Management',
       'Business',
       'Business|Business Strategies|Business Enviorment|New Venture Planning|Foreign Business|Business Organisation',
       'Marketing|Principles Of Marketing|International Marketing|Promotion And Distribution Decisions',
       'Social Work|NGO', 'Fine Arts|Painting',
       'Legal Studies|Legal System|Legal Tradition|Nationality Law|Government Law',
       'Business|Entreperneurship|Venture Capitalist|Business Enviorment|Start Ups|Business Planning|New Venture Planning',
       'Legal Studies|Company Law|Legal System|Banking Law',
       'Computer Technology|Web designing|Artificial Intelligence|Computer Application|Machine Learning|Frontend Development',
       'Music', 'Sculptures|Wood Crafts|Craft|Wood carving',
       'Fashion Design', 'Painting|Craft|Artistic design',
       '2D Composition|Watercolours|Painting',
       'Painting|Watercolours|2D Composition',
       'Visual Arts|Craft|Conceptual',
       'Painting|Visual Arts|Craft|Conceptual',
       'Painting|Craft|Mixed Media|2D Composition',
       'Visual Arts|Craft|Mixed Media|Conceptual|Mosaic painting',
       'Craft|Drawings|Conceptual|2D Composition',
       'Craft|Mixed Media|Conceptual|Mosaic painting|2D Composition',
       'Video',
       'Fashion Desigining|Fashion Illustration|Pattern Cutting|Fashion Communication',
       'Biotechnology|Animal Biotechnology',
       'Fashion Desigining|Pattern & Culture|Fashion Trends|Fashion Portfoilio',
       'Sketch Video',
       'Fashion Desigining|Pattern & Culture|Fashion Textile|Fashion Trends',
       'Test', 'Professionalism', 'Art', 'Science;Technology',
       'Art; Science',
       'Fashion Design|Illustration|Watercolours|Drawings',
       'Drawings|Fashion Design|Illustration|Watercolours',
       'Fashion Design|Illustration|Watercolours',
       'Drawings|Fashion Design|Mixed Media|Conceptual|Illustration|Pen and ink|Watercolours',
       'Fashion Design|Illustration|Conceptual|Watercolours|Pen and ink',
       'Artistic design|Logo Design|Graphic|Illustration',
       'Visual Arts|Graphic Design|Artistic design|Graphic|Illustration',
       'Learning', 'Photography|Architecture|Visual Arts|Graphic Design',
       'Photography|Architecture|Visual Arts|Graphic Design|Artistic design|Graphic|Logo Design',
       'Visual Arts|Graphic Design|2D Composition|Logo Design',
       'Artistic design',
       'Literature|Stories|Fictions|Movements in Literature',
       'Technology',
       'Computer Technology|Computation|Computer Application|Cloud Computing',
       'Visual Arts|Calligraphy|Pen and ink',
       'Mixed Media|Calligraphy|Pen and ink', 'Typography|Pen and ink',
       'Typography|Calligraphy|Pen and ink',
       'Calligraphy|Typography|Pen and ink', 'Calligraphy|Pen and ink',
       'Mass Media|Media And Society', 'Science; Technology'],
      dtype=object)